version: '3.8'

services: 

  web:
      build: .
      ports:
        - 8014:8000
      command: uvicorn app.main:app --host 0.0.0.0 --reload
      volumes:
        - .:/email-service/
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
        - TZ=US/Eastern
      depends_on:
        - redis

  redis:
    image: redis:7

  worker:
    build: .
    command: celery -A app.worker.celery worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - .:/email-service/
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TZ=US/Eastern
    depends_on:
      - web
      - redis  
      
  dashboard:
    build: .
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TZ=US/Eastern
    depends_on:
      - web
      - redis
      - worker   
